### ISSUE TITLE
How do I get the credentials

### ISSUE THREAD

**Issue by ghost** [aperpen/clash-royale-client#1]
I think this project is really awesome! But it would be nice to mention in the readme file how exactly you can get the credentials. So I don‘t know how to do it 👍🏻

**Comment by aperpen** [comment]
Hi! 
The easiest way is to proxy them, I think the best proxy atm is this: https://github.com/Galaxy1036/RC4toSodiumProxy.

Credentials are sent on the [Login packet (10101)](https://github.com/royale-proxy/cr-messages/blob/master/client/Login.json). If you have any doubts about how does cr protocol work you can read the most important stuff [here](https://github.com/clugh/cocdp/wiki).

**Comment by jakob-kruse** [comment]
Most likely beginners wont understand this explanation. Maybe you could give an example? Would be awesome.

**Comment by aperpen** [comment]
Guide about How to get credentials added to the readme
