### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by nagayev** [aperpen/clash-royale-client#15]
I can't login.
My config.js file almost is the same to config.example with my pass from 
storage_new.xml and my tag.
Maybe new key server key for Clash Royale 2.4.3?

**Comment by nagayev** [comment]
@aperpen I fixed this problem.
But commands don't work except command top

**Comment by nagayev** [comment]
Question:
In packets I find ClanChat but there is no command.
Why?

**Comment by aperpen** [comment]
When I tried the packet wasn't working and I couldn't look it further.
