### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by princeoftulip** [aperpen/clash-royale-client#8]
I tried to install your client, but it always seems to be failed... "npm ERR!" exit status 1" 
Could you please, contact with me in Telegram? My username is @prayidie

**Comment by aperpen** [comment]
Mmmm... Could you provide the full error log?
I don't have Telegram, but you can contact me on Discord: AN#1574

**Comment by princeoftulip** [comment]
@aperpen okay, I have installed your client, putted my passtoken (from storage_new.xml) and tag, but it's crashed anyway...

**Comment by aperpen** [comment]
It's an issue with Supercell ID login definiton, regular tokens work as expected. Will fix ASAP.
